[package]
name = "pnp"
version = "0.9.1"
edition = "2021"
license = "BSD-2-Clause"
description = "Resolution primitives for Yarn PnP"
homepage = "https://yarnpkg.com"
repository = "https://github.com/yarnpkg/pnp-rs"

[dependencies]
arca = "^0.7"
byteorder = "1"
concurrent_lru = "^0.2"
fancy-regex = "^0.13.0"
indexmap = { version = "2.7.1", features = ["serde"] }
lazy_static = "1"
miniz_oxide = "^0.7"
mmap-rs = { version = "^0.6", optional = true }
pathdiff = "^0.2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = {  version = "3", features = ["indexmap_2"] }
thiserror = "1"

[dev-dependencies]
rstest = "0.25.0"

[features]
mmap = ["dep:mmap-rs"]
